# ============================================================
# Copie ce fichier en application-dev-TONPRENOM.properties
# Remplis tes valeurs perso, ne JAMAIS le commiter.
# ============================================================

# Base de données
spring.datasource.password=TON_MOT_DE_PASSE_POSTGRES

# JWT
jwt.secret=GENERE_AVEC_openssl_rand_base64_64

# Email
spring.mail.username=ton.email@gmail.com
spring.mail.password=ton_app_password_gmail

# Campay Integration (Module Paiements - Shinley)
# Ne pas modifier ces valeurs, elles sont partagées par toute l'équipe
campay.base.url=https://demo.campay.net/api/
campay.access.token=a7661a7e2f38ced24684d8f1c40258c4749bb8d2
campay.webhook.url=http://localhost:8080/api/v1/payments/webhook/campay
campay.redirect.url=http://localhost:3000/payment/success